### ISSUE TITLE
"Help: Report Issue" points user to the wrong issue tracker

### ISSUE THREAD

**Issue by mikemol** [MicrosoftDocs/vscodespaces#569] opened 2020-06-07 03:19 UTC
Inside of Visual Studio Codespaces, if you bring up the command palette and hit `Help: Report Issue`, it takes you to https://github.com/microsoft/vscode/issues instead of https://github.com/MicrosoftDocs/vsonline/issues . This led me to filing #568 in the wrong place, initially.

**Comment by jkeech** [comment] 2020-06-08 16:54
I think this is currently By Design, although we are considering changing the behavior. It works this way because you are running VS Code in the browser, and those are all of the built-in hooks to send feedback for VS Code (same as in the desktop VS Code). It's not clear yet whether the majority of issues that users will file will be related to Codespaces specifically or if they will be VS Code issues/feedback. Whichever one is more common will drive our decision about where to direct feedback to by default.

More broadly, there are some open design discussions around which parts of the VS Code commands/UI should be tweaked to be more Codespace-specific vs match VS Code on the desktop, but generally VS Code in the web should match VS Code on the desktop by default and only diverge when there is a specific need. cc @nikmd23 

----

One way to report a Codespaces-specific issue today is through the Remote Explorer viewlet. If you select Codespaces from the dropdown in the Remote Explorer, then go to the Help and Feedback section at the bottom, you can click on Report Issue, which will take you to this repo.

![image](https://user-images.githubusercontent.com/746020/84057980-65a40980-a96d-11ea-9d95-60b8b50ce975.png)

**Comment by lostintangent** [comment] 2020-09-11 04:18
Closing this as by design per the previous comment.

**Closed by lostintangent** 2020-09-11 04:18 UTC
Labels: ux
