### ISSUE TITLE
On self-hosted instances Codespaces spawns vsls-agent processes until the instance runs out of memory

### ISSUE THREAD

**Issue by janus-reith** [MicrosoftDocs/vscodespaces#762] opened 2020-08-22 15:50 UTC
As desribed in https://github.com/MicrosoftDocs/vscodespaces/issues/720#issuecomment-670981082 and https://github.com/MicrosoftDocs/vscodespaces/issues/720#issuecomment-671072623, the `codespaces` agent will constantly spawn `vsls-agent` processes, each spiking at 100 % CPU usage for a short time.
I had that behaviour on four instances running Ubuntu 18.04 which I registered as headless, and one OSX device / iMac were I used the VSCode extension to add it.

My linux systems run out of memory after a short time and become unusable. On OSX the machine stayed kind of responsive, but kept killing new processes, logging to console that too much file handles are kept open.
I assume the underlying reason is the same of too many` vsls-agent`'s running.

The machines stay resonsive if I rename or remove `/opt/codespaces/bin/vsls-agent`, but at that point Codespaces also won't connect.

**Comment by janus-reith** [comment] 2020-08-23 19:45
Thanks, let me know if there's any helpful details I could provide!

**Comment by kumarz** [comment] 2020-08-25 05:04
I have followed this up and came to know that the team is aware of this and the fix is ready.
cc: @smvanderweide, @khkh-ms, @Davsterl

**Comment by janus-reith** [comment] 2020-08-29 13:44
@kumarz Is there any way for me to check out that fix somehow already? As far as I got it, vsls-agent seems to be a separate project called live-share, and I‘m not sure yet how things are related.

**Comment by lorenpaulsen** [comment] 2020-09-28 23:12
Closing, as this issue is a duplicate of #655, which has been fixed and deployed.

**Closed by lorenpaulsen** 2020-09-28 23:12 UTC
Labels: area: self-hosting
