### ISSUE TITLE
Add a Python environment manager to the universal image

### ISSUE THREAD

**Issue by GraemeMalcolm** [MicrosoftDocs/vscodespaces#211] opened 2019-11-22 17:12 UTC
I can’t seem to install the Azure ML SDK in Visual Studio Online environment. I get the following error installing the azureml-dataprep dependency:

```
ERROR: Could not find a version that satisfies the requirement azureml-dataprep-native<14.0.0,>=13.1.0 (from azureml-dataprep[fuse]<1.2.0a,>=1.1.29a->azureml-sdk) (from versions: none)
Cleaning up...
ERROR: No matching distribution found for azureml-dataprep-native<14.0.0,>=13.1.0 (from azureml-dataprep[fuse]<1.2.0a,>=1.1.29a->azureml-sdk)
```
Repro steps:

1. Create a new VSO Environment (Linux, Basic)
2. Install the Microsoft Python extension and reload.
3. Open a terminal and enter the command `pip install azureml-sdk`
4. Package download starts, but ends with the error message above.

**Comment by lostintangent** [comment] 2019-11-22 22:28
I'm not a Python expert, so I don't know if this makes sense, but I wonder if the problem is that the `azureml-sdk` module doesn't currently support Python 3.8? That's the default version of Python within environments, and I can definitely repro this error. However, as soon as I explicitly use Python 3.6 or 3.7, then the installation works. So 3.8 seems to be related to the issue.

Here's a screenshot from the [PyPi page](https://pypi.org/project/azureml-sdk/) for `azureml-sdk`, which seems to omit 3.8 from the list:

![image](https://user-images.githubusercontent.com/116461/69464759-1af5d380-0d34-11ea-8cce-b584d3aba5c3.png)

**Comment by GraemeMalcolm** [comment] 2019-12-04 18:50
Python 3.5 is also installed (as well as 2.7), but there's no pip installed for those environments, so you can;t pip install any packages into them. Also conda  does not seem to be installed, so you can't easily switch Python environments in the terminal.

I think we need support for working in different python environments, and not just the latest 3.8.

**Comment by Veda226** [comment] 2019-12-24 12:39
did you get an solution?

**Comment by leestott** [comment] 2020-03-10 19:49
@GraemeMalcolm  you can use custom docker images so this should resolve the issue :-) here are some templates 
https://github.com/microsoft/vscode-dev-containers/tree/master/containers/

**Comment by lostintangent** [comment] 2020-09-11 04:35
Closing this as resolved, per @leestott's comment. Please re-open it if this is something that we still need to look into. Thanks!

**Closed by lostintangent** 2020-09-11 04:35 UTC
Labels: area: kitchensink, area:customization, enhancement, language: python
