### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by Maxim-Filimonov** [MicrosoftDocs/vscodespaces#261] opened 2019-12-17 15:17 UTC
On safari(iPad OS 13.2) i receive the following error when trying to share storybook based web server. It works locally without problem and through ngrok. Presume the issue is somehow with port forwarding through vs online
**Error:**
FetchEvent.respondWith received an error: Error: ClientDoesNotExist
**URL:**
https://5f983d93c54d42a8a6d44990e562621539e7-9009.app.online.visualstudio.com/

**Comment by nikmd23** [comment] 2019-12-20 22:07
Thanks for the report @Maxim-Filimonov!

Would you mind providing the repro steps, or a repo we can clone that reproduces this issue? That'd greatly help us to figure out a fix for this.

**Comment by Maxim-Filimonov** [comment] 2019-12-23 18:22
It's a private repo I cannot provide it. :[

**Comment by lostintangent** [comment] 2020-10-12 15:28
Closing this as resolved, since we've since shipped a brand new port forwarding service. Please re-open this if you're still running into issues. Thanks!

**Closed by lostintangent** 2020-10-12 15:28 UTC
Labels: area: port forwarding, bug
