### ISSUE TITLE
VS Online defaults to wrong tenant, doesn't allow me to select tenant & subscription

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/vscodespaces#464] opened 2020-05-07 14:21 UTC
# Issue
The account I log in with is in the `domain1` tenant. I am also a guest external AAD admin in the `domain2` and `domain3` AAD tenants.

`domain2` user status:
![image](https://user-images.githubusercontent.com/15258962/81305553-51e64a00-9033-11ea-9c7e-c44c130ffb0d.png)

When I log in using my domain1 account at domain1.onmicrosoft.com, I'm getting `domain2` tenant subscriptions instead of `domain1` when trying to create a codespace, with no way to select another. For some reason it is selecting `domain2` even though it's not my original login.

![image](https://user-images.githubusercontent.com/15258962/81305077-c2d93200-9032-11ea-8dd9-35272f2f235b.png)

I also confirmed when I logged in that I was logging in for the tenant I was associated, I even tried forcing the login with special login URL to ensure that it wasn't "assuming" my tenant.

# Resolution Criteria

1. This dialog should always default to the tenant the user originates in
2. It should offer an option to list tenants if the user exists in multiple tenants, just like Azure Portal does:
![image](https://user-images.githubusercontent.com/15258962/81305367-1a779d80-9033-11ea-8696-2f9ed786f3a7.png)

**Comment by JustinGrote** [comment] 2020-05-07 14:26
This is related to #39 except I'm getting my **non-default** AAD tenant. If there's somewhere specific maybe I'm missing where to set this and somehow it got changed, let me know.

**Comment by jkeech** [comment] 2020-05-21 16:02
The "default" tenant selection in the Azure portal just changes your preferences for the Azure portal, and doesn't change which tenant is considered the home tenant in AAD.

The problem is outlined in a bit more detail at https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant#update-your-code-to-send-requests-to-common

> When Microsoft identity platform receives a request on the /common endpoint, it signs the user in and, as a consequence, discovers which tenant the user is from. The /common endpoint works with all of the authentication protocols supported by the Azure AD: OpenID Connect, OAuth 2.0, SAML 2.0, and WS-Federation.
>
>The sign-in response to the application then contains a token representing the user. The issuer value in the token tells an application what tenant the user is from. When a response returns from the /common endpoint, the issuer value in the token corresponds to the user’s tenant.

I think you are running into the same problem as #39 where we only support the home tenant today.

**Comment by JustinGrote** [comment] 2020-05-21 16:04
@jeech except my home tenant is not the one that is coming up in Codespaces.

**Comment by lostintangent** [comment] 2020-10-11 19:30
Closing this as a duplicate of #550, so that we can consolidate the discussion around multi-tenant support.

**Closed by lostintangent** 2020-10-11 19:30 UTC
