### ISSUE TITLE
Azure Codespace cannot start VSCode 1.47.3

### ISSUE THREAD

**Issue by nemosupremo** [MicrosoftDocs/vscodespaces#727] opened 2020-08-10 01:11 UTC
When trying to open my codespace with VSCode, the process fails with the following error:

```
[Client V] Initializing authentication
[Client I] Trace log: /var/folders/wg/w4h86dmj65d4qzmjbk_4v7700000gn/T/vsonline_logs/20200810_010639_15970215996590_VSCode.log
[Client I] User logged in as [email]
[Client V] Initializing self-hosted environment registry
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
[VSOnlineResolver I] Resolving: 795536d3-b42a-41f4-90b5-71bbff9ce069 with params undefined
[VSOnlineResolver I] Fetching codespace details
[VSOnlineResolver E] Resolve failed: TypeError: Cannot read property 'length' of undefined
[EnvironmentDetailsExplorer I] Updating environment details
```

Connecting via the browser (https://online.visualstudio.com/) works fine. 

* VSCode v1.47.3
* VSCodespaces v1.0.2621

**Comment by NCC1701M** [comment] 2020-08-10 05:04
Same problem here. An immediate problem fixing is necessary!

**Comment by nemosupremo** [comment] 2020-08-11 23:20
Issue still ongoing, now I'm getting:
```
Failed to connect to the remote extension host server (Error: Unsupported Account Provider: undefined)
```

**Comment by 2percentsilk** [comment] 2020-08-11 23:23
Can you go to Settings > Extensions > Visual Studio Codespaces and then check the account provider? It needs to be set as Microsoft. You will probably have to restart VS Code after you change the Provider and try to sign in to your account again.

**Comment by NCC1701M** [comment] 2020-08-12 11:58
> Can you go to Settings > Extensions > Visual Studio Codespaces and then check the account provider? It needs to be set as Microsoft. You will probably have to restart VS Code after you change the Provider and try to sign in to your account again.

It already was set to Microsoft. I set it again. Now always when I open a codespace project by VSCodes jump list, VSCode forces me to sign in but that fails.

When I open a new VSCode and F1 > Connect to Codespace it works. Until last week also opening via jump list worked fine.

**Comment by 2percentsilk** [comment] 2020-08-13 05:32
@cmbrose any ideas?

**Comment by cmbrose** [comment] 2020-08-13 18:42
>VSCode forces me to sign in but that fails.

@NCC1701M could you explain that behavior a little more?

**Comment by NCC1701M** [comment] 2020-08-13 19:04
I'll do the following:

1. Right click on the VSCode icon
2. Click on a previous opened Codespace project
3. VSCode tries to load the project
4. VSCode shows me the notifcation, that I have to sign in first
5. VSCode opens browser (Chrome) for signing in
6. Sign in with my account
7. Browser asks me to open the given link in VSCode
8. Open the link with VSCode by clicking the Browser dialog

The VSCode either ignores the login or it fails to validate it. Instead it opens a new browser tab where I have to sign in again, then all the same happens beginning at 5. 

Hope that helps a little more.

**Comment by cmbrose** [comment] 2020-08-14 18:09
@NCC1701M - thanks for the details! I can repro using these steps, will work on a fix. In the meantime, I was still able to connect to the codespace by opening VS Code (not in a Codespace context) and selecting the Codespace to connect to through the remote explorer. Are you also able to do that in order to unblock yourself in the meantime?

@nemosupremo - is your repro the same as the one above?

**Comment by NCC1701M** [comment] 2020-08-14 19:05
@cmbrose Yeah I figured it out that connecting via the "normal" VSCode installation works. Thanks

**Comment by nemosupremo** [comment] 2020-08-14 19:16
Nope - I'm not told to login first, when I click a previously opened project I get 

```
Failed to connect to the remote extension host server (Error: Cannot read property 'length' of undefined)
```

FWIW, this process works:

1. Sign in to https://online.visualstudio.com/
2. Click Open with VSCode

**Comment by cmbrose** [comment] 2020-08-14 23:34
Thanks @nemosupremo and @NCC1701M for all the details - I've found the cause of both issues (they are different, but related).  I've checked in a fix now which will be going out in next week's extension release.

@nemosupremo - you should also be able to work around this in the meantime by selecting the Codespace directly in the remote explorer instead of from the reopen list. Can you let me know if that works for you?

**Comment by nemosupremo** [comment] 2020-08-15 03:05
Yes, connecting via the codespace explorer works.

**Comment by cmbrose** [comment] 2020-08-24 20:27
@nemosupremo and @NCC1701M - the new extension version with these fixes was published last Friday.  Could you check and confirm that things are working as expected again?  Thanks!

**Comment by cmbrose** [comment] 2020-08-28 19:43
I'm going to go ahead and close this since the expected fix is out now - if you do still see the issue feel free to reopen!

**Closed by cmbrose** 2020-08-28 19:43 UTC

**Comment by NCC1701M** [comment] 2020-08-29 07:52
> @nemosupremo and @NCC1701M - the new extension version with these fixes was published last Friday.  Could you check and confirm that things are working as expected again?  Thanks!

@cmbrose I'm on vacation right now. So I can't test this right now. I'll going to test this as soon as I'm back

**Comment by NCC1701M** [comment] 2020-09-08 15:57
> 
> 
> @nemosupremo and @NCC1701M - the new extension version with these fixes was published last Friday. Could you check and confirm that things are working as expected again? Thanks!

It works for me
