### ISSUE TITLE
dotfile script folder reference misleading in settings

### ISSUE THREAD

**Issue by MSFTJim** [MicrosoftDocs/vscodespaces#808] opened 2020-09-23 00:04 UTC
The folder reference for "install.sh" in settings and docs lists it as "~/dotfiles/install.sh".  After setting up a dotfiles repo and creating a Codespace I received the error: "bash: /root/dotfiles/~/dotfiles/install.sh: No such file or directory".

I modified the settings value for the Install Command to just be "install.sh" and then Codespaces finds the script file properly and can execute it.

We might want to clarify the wording or change the values for this option.

**Comment by lostintangent** [comment] 2020-10-11 19:45
Closing this as a duplicate of #323.

**Closed by lostintangent** 2020-10-11 19:45 UTC
