### ISSUE TITLE
All of my Codespaces are gone

### ISSUE THREAD

**Issue by dbanisimov** [MicrosoftDocs/vscodespaces#784] opened 2020-09-03 15:23 UTC
I cannot see any of my codespaces under my plan. Moreover 4 new plans were added to my account that I haven't created - all of them have a name `github-auth-fixed-<region_name>`

The last time codespaces were available is approximately at 10pm on Sept 2 (PST).

Subscription id: c7f728b0-0fc8-4e71-95c2-3cf560346f8d

**Comment by mugenwc41** [comment] 2020-09-03 15:29
I had the exact same issue that occurred yesterday (9/1). I deleted the associated resource group in the Azure portal to start over. Now I am unable to create a Codespaces billing plan via VS Code. The error I am getting is: "Create New Codespace: Could not determine plan location". I cannot create the Codespaces through a web browser (Chrome) either, although this is a different issue. The issue is that it does not load the subscription in the drop-down box that is associated to my Visual Studio Enterprise account that has my Azure credits.

**Comment by derekbekoe** [comment] 2020-09-03 16:00
@dbanisimov Thanks for reporting this. We are aware of the issue and are investigating.

**Comment by dbanisimov** [comment] 2020-09-03 16:30
Codespaces in my plan are back and I was able to successfully resume them.

**Comment by jkeech** [comment] 2020-09-03 16:50
@mugenwc41, this issue should be fixed now. Can you try creating a new plan/codespace?

**Comment by dbanisimov** [comment] 2020-09-03 16:54
Just confirming that `github-auth-fixed-<region_name>` plans are no longer present under my account. Thanks folks! 👍

**Comment by jkeech** [comment] 2020-09-03 17:15
Thanks for confirming and apologies for the disruption. I'm going to close this issue, but please do let us know if you see any other problems.

**Closed by jkeech** 2020-09-03 17:15 UTC
