### ISSUE TITLE
allow logging into .NET Core MVC C# app using Azure AD

### ISSUE THREAD

**Issue by LukeStephen** [MicrosoftDocs/vscodespaces#183] opened 2019-11-14 00:32 UTC
I run debugging from Visual Studio Online and after logging into Azure AD it tries to redirect me back to localhost and not to the the long visual studio online URL my application is exposed on for me.

The redirect post azure Active Directory login fails and I can't login to my app to actually debug anything. I tried to add the Visual Studio url as an azure ad redirect url but that didn't help.

**Comment by lostintangent** [comment] 2019-11-14 05:40
When you start debugging, how are you opening up the web page? Clicking the URL in the integrated terminal? Or does your launch configuration automatically open it up? 

From your description, it sounds like your app is configured to use HTTPS, and you’re opening the HTTP URL, which then redirects you back to the HTTPS port. However, when the app does the redirect, it’s redirecting you back to local host, and not the full URL that VSO mapped to the forward port.

Is that possibly the problem? If you explicitly navigate to the HTTPS port, does that seem to work?

**Comment by jkeech** [comment] 2019-11-14 05:53
@lostintangent, the AAD reply url is probably localhost, so the client-side redirects are trying to land back on localhost. I think the old way to configure this would be to have the app redirect back to the dynamically constructed port forwarding url. It would be a bit of a pain though. I don’t think there’s a great solution for this scenario today. The redirecting happens all client side in the browser, so there’s no way to intercept “localhost” and reroute to the other url.

**Comment by lostintangent** [comment] 2019-11-14 06:16
@jkeech Got it. So the general issue is with a forward web app performing a redirect to “localhost”, which we aren’t currently intercepting and translating into the appropriate URL.

I saw this same issue with an ASP.NET Core site, when trying to open its HTTP port, since that redirects you to “local host” on its HTTPS port. So maybe we could use this issue to track the enhancement to rewrite localhost redirects to the full port forwarded URL?

**Comment by jkeech** [comment] 2019-11-14 06:23
In this case, the web app is creating a url for an AAD login OAuth flow, and that AAD url has a redirect uri query param set to a “localhost” url. After AAD finishes logging the user in, they redirect the browser with a 30x redirect back to whatever url they were given. They url also has to be registered in the AAD app backend, so it can’t just be changed at will. We don’t really have any feasible way to intercept those redirects back from AAD.

I believe the only solution currently is to have the app request the right redirect url when constructing the AAD url. And the AAD app registration also needs to have that url included as a possible reply uri, which would unfortunately need to be added/updated each time in AAD.

**Comment by jkeech** [comment] 2019-11-14 06:24
I wouldn’t consider this a bug, more of a limitation with port-forwarding exposing the service on a non-localhost url, when the app is configured for local development to require running on localhost for AAD flows.

**Comment by lostintangent** [comment] 2019-11-14 15:28
Since we’re trying to help “lift and shift” local development to the cloud, I think that means we should try to virtualize the E2E experience as much as possible, so that it just works for folks. I updated the labels to call this out as an enhancement, since I think we should explore doing local host URL rewriting in the future. Outside of this specific scenario, I don’t think it will be too uncommon for a web app to redirect to local host (because that’s the development-time domain), and we should ideally support that.

**Comment by jkeech** [comment] 2019-11-14 15:54
@lostintangent, it’s not just direct redirects issued from the web app. It’s fragments/portions of urls that the web app generates to other services that would need to be rewritten. And for AAD they have security checks to make sure you only use approved redirects. Unless the AAD app registration has the rewritten url, it’s going to fail. The only way to really support this without requiring changing the AAD app registration is to have the site exposed on localhost itself.

**Comment by LukeStephen** [comment] 2019-11-14 17:19
FYI, this all works perfectly in VS Code on my laptop locally. But when using Visual Studio Online with the same project from github I have to specify the forwarding port to 4000

![image](https://user-images.githubusercontent.com/8396657/68879920-48110900-06d8-11ea-962f-f38977019c19.png)

When I navigate to the forwarded port it's already a https connection which is correct and I see my default page of the web application. I then click login which sends me to Microsoft's login page. I even went into Azure AD and added the URL https://b0ded1d5ac534cb9e174be3902bf31d8d6b7-4000.app.online.visualstudio.com as a valid redirect URL and yet it still sends me back to localhost:4000 after login.

**Comment by jkeech** [comment] 2019-11-14 17:24
@LukeStephen, when you construct the AAD uri, you would also need to put that longer url in the `redirect_uri` parameter, as described in the docs at https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#request-an-authorization-code. Could you try that out to see if it works? In theory it should work if you update both the code that is constructing the reply uri and the AAD app registration.

VS Code (desktop) port forwarding works correctly because it is actually taking over that port on localhost and tunneling to the backend. We don't currently have a way to do this from the browser, so we have to expose the site on a different url.

**Comment by LukeStephen** [comment] 2019-11-14 17:52
That is taken care of for me since I'm using openidconnect in my startup.cs, but let me see what I can find to do it myself.

public void ConfigureServices(IServiceCollection services)
{

.AddOpenIdConnect(options => {
                options.Authority = "https://login.microsoftonline.com/common";
                options.ClientId = Configuration["AzureAD:ClientId"];
                options.RemoteAuthenticationTimeout = TimeSpan.FromSeconds(120);
                options.SaveTokens = true;
                options.TokenValidationParameters = new 
            });

**Comment by plisy** [comment] 2019-11-14 18:00
There's two separate issues here. 

1. VSO doesn't rewrite headers on redirect requests properly like reverse proxies do. 
2. We don't add forwarded headers the way reverse proxies do so the apps know how to rewrite their URLs. 

We are looking at fixing both these issues.

**Comment by lostintangent** [comment] 2019-11-23 01:27
@plisy Issue #1 is already being tracked by #128, so I’m wondering if we should update this issue to account for #2? Or if we should close this issue as a duplicate of #128?

**Comment by lostintangent** [comment] 2020-10-11 03:28
Closing this as resolved. Please let us know if you're still running into this issue. Thanks!

**Closed by lostintangent** 2020-10-11 03:28 UTC
Labels: area: port forwarding, area: web editor, enhancement
