### ISSUE TITLE
[Docker Container] postCreateCommand is not executed when the env is resumed after being suspended

### ISSUE THREAD

**Issue by Naninani** [MicrosoftDocs/vscodespaces#773] opened 2020-08-27 17:51 UTC
This is related to docker containers, where the postCreateCommand is not executed when the env is resumed after being suspended.

Steps to reproduce:
1. Create a script in the .devcontainer folder and add
`"postCreateCommand": "bash ./.devcontainer/post-create.sh"`
in the devcontainer.json file.
2. Create new Env.
3. When the env is created the script is executed correcty.
4. Wait for the env to get suspended and resume it.
5. The script is not executed.

Expected result: The script should be executed after the env gets resumed as the container is resumed. Instead the script is not executed and the settings are not being applied to the container.

**Comment by jkeech** [comment] 2020-08-27 18:02
@Naninani, this is by design. The `postCreateCommand` should only execute once after initial Codespace creation. It does not execute every time you connect or every time the Codespace is resumed. 

VS Code has a fairly new `postStartCommand` and `postAttachCommand`, which sound closer to what you are looking for. Codespaces does not support those yet, but #403 is tracking that work. I'm going to close this issue as a duplicate of #403, but let me know if you disagree and we can re-open.

**Closed by jkeech** 2020-08-27 18:02 UTC
