### ISSUE TITLE
No user feedback when opening codespace in VS Code and not signed into extension

### ISSUE THREAD

**Issue by chkn** [MicrosoftDocs/vscodespaces#593] opened 2020-06-17 18:57 UTC
From the portal, if you select Open in VS Code (or Open in VS Code Insiders) on a codespace, VS Code will open and display a message asking if you want to allow the extension to open the URI. If you click Open and the extension is not signed in, nothing happens, and it's not clear that you need to sign in there.

This message is logged to the JS console:

```
workbench.desktop.main.js:sourcemap:265 [Extension Host] rejected promise not handled within 1 second: Error: EnvironmentProvider found no cached tokens (at extensionHostProcess.js:976:42)
t.log @ workbench.desktop.main.js:sourcemap:265
workbench.desktop.main.js:sourcemap:265 [Extension Host] stack trace: Error: EnvironmentProvider found no cached tokens    at t.VsoEnvironmentsApi.getTokenOrThrow (vsoEnvironmentsApi.ts:349:19)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:85:5)    at t.VsoEnvironmentsApi.getEnvironmentList (vsoEnvironmentsApi.ts:250:15)    at updateEnvironmentsInfo (EnvironmentInfo.ts:62:22) (at extensionHostProcess.js:976:121)
t.log @ workbench.desktop.main.js:sourcemap:265
workbench.desktop.main.js:sourcemap:1670   ERR EnvironmentProvider found no cached tokens: Error: EnvironmentProvider found no cached tokens
    at t.VsoEnvironmentsApi.getTokenOrThrow (vsoEnvironmentsApi.ts:349:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at t.VsoEnvironmentsApi.getEnvironmentList (vsoEnvironmentsApi.ts:250:15)
    at updateEnvironmentsInfo (EnvironmentInfo.ts:62:22)
```

**Comment by lostintangent** [comment] 2020-10-11 19:01
@osortega @legomushroom Did we ever address this issue?

**Comment by legomushroom** [comment] 2020-10-12 17:37
cc @cmbrose

**Comment by cmbrose** [comment] 2020-10-21 15:41
I just confirmed that in both VSCS and GH browser, opening in desktop will now trigger login if there's no cached credential so looks like we're good here.

FWIW I did coincidentally find that if you open in desktop from GH and vscode initializes itself into a VSCS environment before trying to connect (because it automatically reloads whatever connection it was in when last closed) then it will fail to open the GH codespace with similarly bad reporting.

I think that this isn't a case we want to invest in fixing though given the roadmap so I'm going to close this one out, but @lostintangent please reopen if that's not the case.

**Closed by cmbrose** 2020-10-21 15:41 UTC
