### ISSUE TITLE
Document available tools and update strategies

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vscodespaces#72] opened 2019-11-05 17:48 UTC
Currently, it seems like there's a set of pre-installed languages/platforms on the VMs. I was *super* happy to find that Node.js 12.13.0 LTS was installed at launch of the public preview, but it would be awesome to have a set of documentation that confirms what's shipping in the images.

Additionally, perhaps a command like `vso available` or something like that (perhaps an open-source tool that is shipped with the images that the community can contribute to?) to easily list out inside of VS Online's VMs themselves.

**Comment by dcarosone** [comment] 2019-11-05 20:58
There is some mention in the docs of multiple linux distro/flavour options, which implies being able to choose image types, but it's only scant and not clear how to do this or where the options are listed.

Further to this, on the question of reproducible builds, how will version management of images be done?

I, personally, would be very happy to get an image with 'up to the minute latest' fresh bits each time. Others have use cases where they want the same compiler/libs/etc they got 'last time' or 'nine months ago when the release being debugged was built'.

It's perfectly ok if this is not there yet for the preview, but it will be a common concern and likely is at least a good FAQ entry to describe what is coming later.

**Comment by lostintangent** [comment] 2019-11-06 02:41
Yeah this is a great reminder! We have a set of "officially" supported runtimes (currently Node.js, Python, PHP and .NET Core), and so we should explicitly call that out, along with what specific tools/versions we install by default.

**Comment by lostintangent** [comment] 2020-09-11 03:58
Closing this for now, since our [Codespaces Devcontainer](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux) specifies the languages/tools it contains. Moving forward, we'll add this detail to the GitHub docs, and so we'll track that as part of a larger round of doc updates we're doing as part of the [transition of Codespaces to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/).

**Closed by lostintangent** 2020-09-11 03:58 UTC
Labels: area: kitchensink, doc-enhancement
