### ISSUE TITLE
Issues when trying to download directories from an environment

### ISSUE THREAD

**Issue by KheireddineAzzez** [MicrosoftDocs/vscodespaces#301] opened 2020-02-10 20:11 UTC
Hi ,  
I have a issue in my azure where i can't download my project that i have created in visual code studio  online , problem is i have to reload my windows and that lead to cancel my download 
![sans-titre](https://user-images.githubusercontent.com/59838139/74185592-3abcd980-4c49-11ea-86e6-1182fcf78df8.png)
![sans-titre1](https://user-images.githubusercontent.com/59838139/74185615-45776e80-4c49-11ea-95cd-994cd5b8afa6.png)
![sans-titre2](https://user-images.githubusercontent.com/59838139/74185657-5de78900-4c49-11ea-931a-62b17d24200e.png)

**Comment by jkeech** [comment] 2020-02-10 20:16
Hi @khandelwalbrijesh, sorry you are hitting this issue. Are you using the web editor or the VS Code desktop extension?

**Comment by KheireddineAzzez** [comment] 2020-02-10 20:43
yes
________________________________

**Comment by jkeech** [comment] 2020-02-10 20:48
@khandelwalbrijesh, can you clarify which version you are using? Do you access the environment from the browser, or do you instead access from VS Code that is installed on your machine?

**Comment by lostintangent** [comment] 2020-04-04 19:24
@jkeech The screenshots look like VS Code
Desktop. Do we currently support downloading directories?

**Comment by jkeech** [comment] 2020-04-04 19:41
@lostintangent, VS Code does support directory downloads. We don't do anything special for this other than provide the connection to the remote side -- the download logic is all built into VS Code.

I wonder if there is some sort of perf issue with large directories somehow either hogging too much bandwidth or otherwise starving the connection, causing it to drop in the middle of the download. I haven't been able to reproduce this, although I've only tried with uploading/downloading smaller directories.

**Comment by lostintangent** [comment] 2020-10-11 19:43
Closing this as a duplicate of #282.

**Closed by lostintangent** 2020-10-11 19:43 UTC
Labels: bug
