### ISSUE TITLE
Infinite login loop

### ISSUE THREAD

**Issue by acgetchell** [MicrosoftDocs/vscodespaces#532] opened 2020-05-22 13:20 UTC
I am logging in using my UC Davis campus account. It looks like it’s getting bounced due to our use of Duo 2-factor.

**Comment by lostintangent** [comment] 2020-09-12 16:59
@legomushroom Any thoughts here? Is the use of MFA an issue here?

**Comment by legomushroom** [comment] 2020-09-12 17:22
2FA should not be an issue unless that is some specific college 2FA step that blocks us so would be great to get more info.

@acgetchell what browser and what OS do you use to sign in? Can you provide more info on the issue so we can investigate?

**Comment by lostintangent** [comment] 2020-10-12 15:10
Closing this as a duplicate of #75.

**Closed by lostintangent** 2020-10-12 15:10 UTC
Labels: area: authentication, bug
