### ISSUE TITLE
Drag and drop large files (> 80MB)

### ISSUE THREAD

**Issue by aeisenberg** [MicrosoftDocs/vscodespaces#517] opened 2020-05-19 20:41 UTC
I am using codespaces for this workspace: https://github.com/aeisenberg/vscode-codeql-starter. Part of the workflow is for users to upload archive files into the workspace through drag and drop. My experience is that archive files of ~40MB can be uploaded with no problem. But archives of ~80MB cannot be. When I try to drag and drop large files, the operation silently fails. Is this expected and is there any workaround I can do?

**Comment by jkeech** [comment] 2020-05-19 21:01
This looks like the inverse of #292, #509. From @legomushroom offline:

> From my experience, there is no limit but the file upload takes up the connection bandwidth so at some point VSCode client and server cannot communicate and the connection times out. Once you hit that, you will see the reload modal and the client will be reloaded, - that will break the uploading process. Hence it really depends on the connection speed you have + the file size you are trying to upload.

cc @legomushroom @bpasero

**Comment by bpasero** [comment] 2020-05-20 05:57
Could be https://github.com/microsoft/vscode/issues/83565

@isidorn

**Comment by isidorn** [comment] 2020-05-20 08:27
Yeah feels like a duplicate.

**Comment by bpasero** [comment] 2020-05-20 13:05
@aeisenberg can you share such a file for me to reproduce? I was just now able to upload a >100MB file when testing locally.

**Comment by aeisenberg** [comment] 2020-05-20 15:38
Here's a link to one I'm hosting. 

https://drive.google.com/file/d/1J-cF468nUqlEeAkSuussfajXi5FyGheY/view?usp=sharing

@bpasero did you test on a local machine or are you connecting remotely? If the problem is indeed related to bandwidth, have you tried artificially throttling your upload speed and seeing if you can reproduce that way?

**Comment by bpasero** [comment] 2020-05-20 16:10
Tested locally. Do you see errors in devtools when this fails?

**Comment by aeisenberg** [comment] 2020-05-20 18:26
There are no errors directly in the UI, though the page goes into a reconnection loop. I'm attaching the devtools log output here, which may contain some useful details.
[github.com-1589999110175.log](https://github.com/MicrosoftDocs/vsonline/files/4658642/github.com-1589999110175.log)

**Comment by bpasero** [comment] 2020-05-22 14:12
Yes, I was able to reproduce the reconnection dialog as well, but cannot tell why that happens in codespaces.

**Comment by lostintangent** [comment] 2020-10-11 18:54
@bpasero Is this still an outstanding issue?

**Comment by bpasero** [comment] 2020-10-12 08:24
Yeah I am quite sure this can be closed given fixes I did in this area to reduce IO pressure on upload.

**Comment by lostintangent** [comment] 2020-10-12 13:58
@bpasero Thanks for confirming that!

I’ll close this as resolved then, but if anyone runs into issues here, please feel free to re-open it. Thanks!

**Closed by lostintangent** 2020-10-12 13:58 UTC
