### ISSUE TITLE
CTRL+V to paste broken for Python notebooks

### ISSUE THREAD

**Issue by GraemeMalcolm** [MicrosoftDocs/vscodespaces#758] opened 2020-08-20 23:31 UTC
After today's update (Aug 20th), I can't paste into cells in a Jupyter notebook using CTRL+V.
SHIFT+CTRL+V does work.

Is this by design?

**Comment by nikmd23** [comment] 2020-08-26 17:41
Hey @GraemeMalcolm! Are you using VS Code desktop in this scenario, or the web editor?

Can you paste in other places? (Different file types, the terminal, etc)

**Comment by GraemeMalcolm** [comment] 2020-08-26 19:07
It only happens in Python notebooks in VS Codespaces. I can use all the CTRL+X, C, and V shortcuts in other types of files - just not in cells in a notebook. I don;t experience the problem in VS Code locally (with the latest updates), just in Codespaces.

**Comment by luabud** [comment] 2020-08-26 20:14
I can also reproduce the issue, I tried an older version of the Python extension just in case but the problem persists.

**Comment by GraemeMalcolm** [comment] 2020-08-28 19:49
@nikmd23 @luabud, any further news on this?

**Comment by luabud** [comment] 2020-08-28 20:26
Everything works as expected locally, I believe the issue is really in codespaces. @nikmd23 if there's anything I can do to try to help with debugging it, please let me know!

**Comment by nikmd23** [comment] 2020-08-28 22:27
This conversation is a bit forked on the internal email as well. @jkeech was asking for a bit more info @GraemeMalcolm. Was this in GitHub or VS Codespaces, and are you on Insiders or Stable?

**Comment by jkeech** [comment] 2020-08-28 23:21
Adding @bpasero and @mjbvz. Sounds like this repros on both insiders and stable in the web.

**Comment by dimaai** [comment] 2020-09-01 08:42
Adding to this: for me Ctr+c/ Ctr+V doesn't work - tested in Edge and Chrome. Paste I could do with Ctr+Shft+V (not Vtr+V though!), but copy couldn't manage to do.
This is a disaster to code without copy-paste working!

**Comment by GraemeMalcolm** [comment] 2020-09-02 16:46
@jkeech - any news on this?

**Comment by jkeech** [comment] 2020-09-02 17:08
@GraemeMalcolm, I think this is a VS Code web issue, which is why I looped in @bpasero and @mjbvz. I haven't heard back from VS Code yet about this issue.

**Comment by bpasero** [comment] 2020-09-03 06:24
Sorry, I am not an expert in this area, but I can try to ask some questions until Matt finds the time to chime in:
* does this reproduce in stable and insiders?
* my understanding is that the Python notebook is probably still using `webview/iframe` and not our new notebook infrastructure, if that is true, does this reproduce with other extensions that use `webview/iframe` and allow to paste?
* does this reproduce in other browsers and on other OS

I think I am getting to a minimal repro, provided my assumption this is a `iframe` issue holds true:
* install `tht13.html-preview-vscode`
* create a new HTML file
* add `<input>` element
* preview it
* try to copy/paste/cut using keybindings

=> it does not work
=> it works fine in native versions of VSCode

However I can reproduce this already with stable version of VSCode so it does not sound like a recent regression.

**Comment by GraemeMalcolm** [comment] 2020-09-03 14:51
I only see this issue in notebooks in VS Codespaces using a browser.
All CTRL+ shortcuts worked as expected until August 20th (we use them extensively in training modules).
On August 20th, they were working as expected until I suspended and restarted a Codespace to find that the Python extension had been upgraded.
Since then, CTRL+X/C/V do not work in Notebooks in any Codespace.
The Python extension team have repro'd the issue with an older version of the extension, so the upgrade timing may be a coincidence. Was there another update pushed out around the same time?

**Comment by bpasero** [comment] 2020-09-10 06:31
I reported this in our repo as https://github.com/microsoft/vscode/issues/106383. Was able to reproduce in our playground.

**Comment by bpasero** [comment] 2020-09-15 08:06
@jkeech the issue was closed in our repo and is available in todays insider build.

**Comment by lostintangent** [comment] 2020-10-11 18:25
Closing this as resolved per @bpasero's previous comment. Please let us know if you're still running into any issues in this area. Thanks!

**Closed by lostintangent** 2020-10-11 18:25 UTC

**Comment by dimaai** [comment] 2020-10-11 20:32
The issue seems like it is closed now but what is the solution? I still can't do any copy/paste in vs codespaces. Followed comment by @bpasero above but there it also confirms issue, and couldn't find workaround.
