### ISSUE TITLE
Not able to create Plan/Codespace in VS Code Browser

### ISSUE THREAD

**Issue by Gurpreetssandhu** [MicrosoftDocs/vscodespaces#821] opened 2020-10-10 22:42 UTC
I am trying to sign-up for Browser based VS Code. I am not able to create a new Plan using the default (resource groups - auto created) and I have created a separate resource group, but No success either way.

Error: TimeoutWaitingForRegisterResourceProvider

see attached
<img width="1675" alt="Screen Shot 2020-10-10 at 1 06 14 PM" src="https://user-images.githubusercontent.com/29930999/95666502-1e8e7680-0b0f-11eb-904f-ced130f8ccf2.png">

**Comment by lostintangent** [comment] 2020-10-11 18:17
Closing this as a duplicate of #520. We'll track the discussion in that issue. Thanks!

**Closed by lostintangent** 2020-10-11 18:17 UTC
