### ISSUE TITLE
Unable to connect to existing VSO plan: There are no environments available.

### ISSUE THREAD

**Issue by jordanbean1** [MicrosoftDocs/vscodespaces#350] opened 2020-03-17 20:00 UTC
I am unable to connect to an existing VS Online plan & environment in VS Code using the Visual Studio Online extension.

I have an existing VS Online plan & environment I created in the Azure portal.

After installing & configuring the Visual Studio Online extension for VS Code, when I run "VS Online: Connect To Environment", I get a popup saying "There are no environments available. Would you like to create one?" I have tried setting the "vsonline.planFilter" to point to my subscription & resource group, but it cannot see it.

On the "Remote Explorer" window, it cannot see my environment either.

Interestingly, if I create a new environment via VS Code using the extension, it is created in the right subscription & I can connect to it.

**Comment by jkeech** [comment] 2020-03-17 23:23
@jordanbean1, sorry you are having issues. To help troubleshoot, can you try connecting from the browser? When you log in to online.visualstudio.com, do you see your plan(s)/environment(s)?

**Comment by jordanbean1** [comment] 2020-03-18 15:12
If I can get logged into online.visualstudio.com, yes. I am often getting the "infinite login loop" issue as well (click the Sign In button, a new window pops up asking what ID I want to use, I select an ID, a new window pops up with the same Sign In button). If I try to create an environment with the same name in VS Code after creating a new one, I get an error saying it already exists.

**Comment by jkeech** [comment] 2020-03-18 15:21
@jordanbean1 what happens if you run the "VS Online: Select Plan" command? Does it list your plans? And if you select the one with your environment, does it then show up in the list on the side?

**Comment by jordanbean1** [comment] 2020-03-18 15:34
Yesterday, it said I had no plans, but today it is allowing me to select the plans and they show up in the "Remote Explorer". I cleared my cookies this morning to try to get around the "infinite login loop" issue. Is there a way to better debug when this happens (extra logging, etc)?

**Comment by jkeech** [comment] 2020-03-18 15:44
Good to hear that the plans and environments are showing up. @cmbrose is looking into why the plan selection is not happening by default. The current behavior is definitely confusing.

The login issue in the portal is being tracked in #348. Lots of people are hitting it, and @legomushroom is working on a fix.

**Comment by jordanbean1** [comment] 2020-03-18 15:48
I'm sure part of the issue is the ID I normally use is B2B shared into another tenant. Therefore, there are 2 possible subscriptions for a VSO plan to live under. However, I have tried specifying the "vsonline.planFilter" setting to ensure I select the right one. In addition, I have signed out and signed back in with an ID that only exists in the tenant I want to use, but the VS Code extension seems to "remember" the tenant I was previously connected to. I sometimes see VSO environments for the wrong subscription show up.

**Comment by jordanbean1** [comment] 2020-03-18 15:54
If I click on my signed in ID in the status bar that comes from the Azure Account extension, the Command Palette that shows up shows the correct subscription I want to use. However, when I then run "VS Online Select Environment" the list of environments is for the other tenant & subscription that ID is B2B'd with. I feel like something is cached in the background of the VS Online extension because that other subscription & tenant were the ones I was using with a different ID. The currently signed in Azure Account extention ID doesn't seem to be reflecting in the VS Online extension.

**Comment by jkeech** [comment] 2020-03-18 16:01
@jordanbean1, it's not single sign on today, so you do need to sign in to the VSO extension with the same credentials. Unfortunately, our support for non-default tenants doesn't really exist yet. We do have some commands "VS Online: Sign out" and "VS Online: Sign in", but they will take you through the sign in flow in your default tenant without a tenant switcher. #39 is tracking the work to enable multiple tentants.

**Comment by jordanbean1** [comment] 2020-03-18 21:22
Using "vsonline.signout" & "vsonline.signin" seems to resolve most of my issues around which ID is currently in use & which plan/environment will be selected. Are there plans to integrate with the Azure Account extension or to display which ID is signed in in the VS Online extension?

**Comment by jkeech** [comment] 2020-03-18 21:27
@jordanbean1, yes for both. We are working on better single sign on support, but it's likely still a couple months away due to some complexities with a bunch of different scenarios. For printing the current account, we are going to be starting to print a bunch of logs to the output window. We can include the identity/email that is currently signed in in those logs.

**Comment by lostintangent** [comment] 2020-10-11 19:21
@jkeech @legomushroom what's the latest status on this issue?

**Comment by lostintangent** [comment] 2020-10-11 19:28
Actually, I'm going to close this as a duplicate of #550, since we have numerous issues tracking the multi-tenant issue, and I'd like to consolidate them.

**Closed by lostintangent** 2020-10-11 19:28 UTC
Labels: area: authentication, bug
