### ISSUE TITLE
Failed to connect to remove host server (Github Codespace)

### ISSUE THREAD

**Issue by MaximeHeckel** [MicrosoftDocs/vscodespaces#693] opened 2020-07-28 22:08 UTC
Hi 👋 

I've been following the instructions from https://docs.github.com/en/github/developing-online-with-codespaces/connecting-to-your-codespace-from-visual-studio-code to connect my local VSCode (Insider) to Github Codespace (just to give it a try) and ran into the following issue:

```
Failed to connect to the remote extension host server (Error: Fetch codespace list request failed with status 404)
```

```
Unable to open 'blog.maximeheckel.com': Unable to read file 'vscode-remote://vsonline+8bfdb171-347a-4e9d-9e10-1ce809469164/home/codespace/workspace/blog.maximeheckel.com' (Error: Fetch codespace list request failed with status 404).
```

<img width="1427" alt="Screen Shot 2020-07-28 at 6 07 08 PM" src="https://user-images.githubusercontent.com/2974412/88727218-2be5b880-d0fd-11ea-9970-75e37ada6662.png">

I can see my Github codespace on the list and click on it to initiate the connection, however it always fails almost immediately

**Comment by jkeech** [comment] 2020-07-28 22:09
@cmbrose

**Comment by jkeech** [comment] 2020-07-28 22:21
Thanks for reporting this issue! Could the share the logs from the "VS Codespaces" output pane? Also, do you see the same thing when connecting from VS Code Stable (I would expect so, but would like to rule it out)?

**Comment by jkeech** [comment] 2020-07-28 22:31
We were able to find the 404 requests for your account in our logs. We're investigating what is causing it, since that's not expected.

**Comment by MaximeHeckel** [comment] 2020-07-28 22:45
@jkeech here are the logs from the extensions

```
[Client V] Initializing authentication
[Client I] Trace log: /var/folders/t9/y_fv3wx13bddqhf55b8c1t5m0000gn/T/vsonline_logs/20200728_224502_15959763020120_VSCode.log
[GitHubAuthentication I] Successfully signed in from a cached credential
[Client V] Initializing self-hosted environment registry
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
[VSOnlineResolver I] Resolving vsonline: 8bfdb171-347a-4e9d-9e10-1ce809469164
[VSOnlineResolver I] Fetching codespace details
[EnvironmentInfo E] Failed to fetch environments
Fetch codespace list request failed with status 404
Error: Fetch codespace list request failed with status 404
    at t.GitHubApi.listCodespaces (/Users/maximeheckel/.vscode-insiders/extensions/ms-vsonline.vsonline-1.0.2529/src/partners/github/githubApi.ts:38:15)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at t.GitHubEnvironmentsApi.getEnvironmentList (/Users/maximeheckel/.vscode-insiders/extensions/ms-vsonline.vsonline-1.0.2529/src/partners/github/githubEnvironmentsApi.ts:45:15)
    at updateEnvironmentsInfo (/Users/maximeheckel/.vscode-insiders/extensions/ms-vsonline.vsonline-1.0.2529/src/EnvironmentInfo.ts:55:13)
[VSOnlineResolver E] Resolve failed: Error: Fetch codespace list request failed with status 404
[Client E] Failed to update environments list: Fetch codespace list request failed with status 404
Fetch codespace list request failed with status 404
Error: Fetch codespace list request failed with status 404
    at t.GitHubApi.listCodespaces (/Users/maximeheckel/.vscode-insiders/extensions/ms-vsonline.vsonline-1.0.2529/src/partners/github/githubApi.ts:38:15)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at t.GitHubEnvironmentsApi.getEnvironmentList (/Users/maximeheckel/.vscode-insiders/extensions/ms-vsonline.vsonline-1.0.2529/src/partners/github/githubEnvironmentsApi.ts:45:15)
    at t.EnvironmentExplorer.updateInitializationStatus (/Users/maximeheckel/.vscode-insiders/extensions/ms-vsonline.vsonline-1.0.2529/src/treeView/EnvironmentExplorer.ts:80:22)
```

**Comment by jkeech** [comment] 2020-07-28 23:55
Quick update: It looks like VS Code generates at least two different GitHub access tokens. The Settings Sync service generates one with the scope `user:email`, and Codespaces generates one with `['read:user', 'user:email', 'repo', 'write:discussion']`. The `repo` scope is the one that is needed in this particular call, so the Codespaces token will work for listing Codespaces, and the Settings Sync token will not work for listing Codespaces.

For some reason, the client is using the wrong cached token for the request (the one without the `repo` scope). This is why it returns a 404, which is effectively the same as Unauthorized in this case. I'm not able to reproduce this locally, and I don't see exactly where it's going wrong yet, but we are continuing to look into it.

Could you try a couple things to help us root cause the issue better?
1) Disable all extensions except for the Codespaces extension just to see if another extension is setting some state that is causing us to pick up the wrong cached token.
2) Try on VS Code Stable to see if this only reproduces on Insiders for you. There have been some recent auth provider API changes in VS Code which might be related, although I'm not able to reproduce on either Stable or Insiders.

**Comment by MaximeHeckel** [comment] 2020-07-29 13:50
Made it work! So looks like I can only do this on the Insider (VSCode stable doesn't let me sign in with Github and do setting syncs).
I ended up signing out VSCode setting syncs (I used my Github account to sign in). Then codespace would give me an expected error message when trying to connect `Not authenticated`. 
Signed in again another time, then was able to initiate the codespace that I started yesterday without any problem. 😄 

Thank you for your help!

**Comment by jkeech** [comment] 2020-07-29 16:12
Thanks for the details! This still sounds like there's a bug with the interaction between Settings Sync and Codespaces, so I'll leave this open for tracking that.

**Comment by jkeech** [comment] 2020-07-29 23:04
We have a fix for this issue. Should be deploying an updated extension to the marketplace in a few hours.

**Comment by jkeech** [comment] 2020-07-30 03:11
The extension with this fix has been deployed 🚀

**Closed by jkeech** 2020-07-30 03:11 UTC

**Comment by MaximeHeckel** [comment] 2020-07-30 13:48
Thank you for the awesome work @jkeech!
