### ISSUE TITLE
Skip logon page on start visual studio code

### ISSUE THREAD

**Issue by EwertonJordao** [MicrosoftDocs/vscodespaces#713] opened 2020-08-04 12:59 UTC
Issue Type: <b>Feature Request</b>

Hi everyone, when I start my session on visual studio code after install visual studio code spaces always need to logon to persist my credential I try to find the option to skip it on settings but we don't have an option for this.

Thanks you

Extension version: 1.0.2562
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

**Comment by lostintangent** [comment] 2020-09-11 06:05
@legomushroom Any idea what might be going on here?

**Comment by EwertonJordao** [comment] 2020-09-11 16:04
@lostintangent 

I think this issue is closed after implementation of this parameter 

![image](https://user-images.githubusercontent.com/12378570/92947892-fe479b00-f42e-11ea-9762-47ff61cd7518.png)

Before we saw two options Microsoft and GitHub, now with Uninitialized I can't see the toast "Signing in..."

Thanks.

**Comment by EwertonJordao** [comment] 2020-09-11 16:06
ms-vsonline.vsonline my current version v1.0.2779 now

**Comment by legomushroom** [comment] 2020-09-11 16:13
@EwertonJordao just to confirm - you are saying that the issue is fixed after the extension update? cc @cmbrose did you see the issue before?

**Comment by EwertonJordao** [comment] 2020-09-11 17:17
@legomushroom 
Yes, I did nothing to correct the settings, I think it comes after some update. 

When I selected the type for authentication for example Microsoft 
![image](https://user-images.githubusercontent.com/12378570/92953821-c5142880-f438-11ea-8106-269d459a4758.png)

![image](https://user-images.githubusercontent.com/12378570/92953832-c9404600-f438-11ea-8fcd-fcf2b3895edd.png)
 
![image](https://user-images.githubusercontent.com/12378570/92953870-d78e6200-f438-11ea-85a1-777641eed564.png)


but now we have this option Uninitialized and the login page won't load automatically when I initialize vscode

**Comment by legomushroom** [comment] 2020-09-11 18:28
@EwertonJordao I see the issue now, we don't want to prompt for sign in on vscode initialization even for Microsoft/GitHub accounts so the issue is still relevant cc @jkeech @cmbrose

**Comment by jkeech** [comment] 2020-09-11 18:36
@EwertonJordao, does the same re-prompting behavior apply when you select the GitHub account? The credentials should be cached on your machine after the first sign-in and not prompt every time. The extension does need sign-in to be able to query for your list of Codespaces, but I'm not able to reproduce it prompting on every VS Code reload after I sign in once.

**Comment by EwertonJordao** [comment] 2020-09-11 19:56
@jkeech now in this version I can't reproduce too this. But in this version Extension version: 1.0.2562 always when vscode starting I need to inform my credentials.

**Comment by jkeech** [comment] 2020-09-11 20:04
@EwertonJordao, thanks! I'll go ahead and close this down since it's not reproducing on the current version. Please feel free to open a new issue if this comes back up. For Github Codespaces issues, we are moving the discussion over to the [GitHub Community](https://github.community/c/codespaces-beta/45) site. Thanks!

**Closed by jkeech** 2020-09-11 20:04 UTC
Labels: area: authentication, area: vscode, bug
