### ISSUE TITLE
Authenticate to online.visualstudio.com as Active Directory guest user

### ISSUE THREAD

**Issue by gavi-anchorlabs** [MicrosoftDocs/vscodespaces#313] opened 2020-02-20 21:45 UTC
The intention is to authenticate users to Visual Studio Online using a third-party identity provider via Azure's Active Directory Direct Federation.

First-class Active Directory users can authenticate with online.visualstudio.com just fine, but guest users created via [Direct Federation](https://docs.microsoft.com/en-us/azure/active-directory/b2b/direct-federation) cannot.

I believe this context from the Direct Federation documentation is relevant
> Direct federation guest users must sign in using a link that includes the tenant context (for example, `https://myapps.microsoft.com/?tenantid=<tenant id>` or `https://portal.azure.com/<tenant id>`, or in the case of a verified domain, `https://myapps.microsoft.com/<verified domain>.onmicrosoft.com)`. Direct links to applications and resources also work as long as they include the tenant context. Direct federation users are currently unable to sign in using common endpoints that have no tenant context. For example, using https://myapps.microsoft.com, https://portal.azure.com, or https://teams.microsoft.com will result in an error.

Is there a way to provide a `tenant_id` when authenticating to VSO via http://online.visualstudio.com? Without a tenant_id, guest users are prompted to enter a nonexistent MSA password when they should instead be redirected to the third-party IdP.

**Comment by lostintangent** [comment] 2020-03-21 16:27
@legomushroom Any thoughts on this?

**Comment by gavi-anchorlabs** [comment] 2020-03-24 22:43
Alternatively, any advice here for other ways to achieve single sign-on with VSO would be very useful. This is the only thing currently preventing a bulk migration of our developer workstations from our self-managed VMs at our current cloud provider to Azure-managed VMs.

**Comment by lostintangent** [comment] 2020-10-11 19:27
Closing this as a duplicate of #550.

**Closed by lostintangent** 2020-10-11 19:27 UTC
Labels: area: authentication, enhancement
