### ISSUE TITLE
code or code-insiders binary not available when installing dotfiles

### ISSUE THREAD

**Issue by felipecrs** [MicrosoftDocs/vscodespaces#809] opened 2020-09-23 19:34 UTC
The `code-insiders` is not available in `PATH` when the dotfiles installation happens. I need it in order to decide if I should create a shim for `code` as an alias for `code-insiders` or not.

In the logs:

`echo $PATH`
![image](https://user-images.githubusercontent.com/29582865/94060882-7c922e80-fd99-11ea-8e63-8a6f17642bd5.png)

In the integrated terminal:
![image](https://user-images.githubusercontent.com/29582865/94060993-a3506500-fd99-11ea-93f2-79d73782c312.png)

Notice that `.vscode-server` is included in the later.

**Comment by jkeech** [comment] 2020-09-23 19:41
Code and code-insiders are not on the path during dotfiles install because the install does not happen within the context of a specific VS Code server/connection -- it's an async step that can happen either before or after you connect. Code and code-insiders are only on the PATH within a terminal session of an active VS Code session. In fact, if you connect concurrently from both VS Code and VS Code Insiders, you'll see different results since one is stable and one is insiders.

Instead of making that determination at dotfiles install time, the recommended approach would be to have your dotfiles include a script/alias that runs as part of your bashrc or bash profile which will get evaluated on future terminals that are spun up within the context of a VS Code server. This is what we do in the default image for Codespaces: https://github.com/microsoft/vscode-dev-containers/blob/1c37760bd0f247943485852578021e5fba31839a/containers/codespaces-linux/.devcontainer/library-scripts/common-debian.sh#L187-L189

**Comment by jkeech** [comment] 2020-09-23 19:45
To clarify, VS Code injects itself on the `PATH` when you are connected to a specific VS Code server instance, so it's not possible to know which version of the server is running outside of that VS Code server connection (and there could be multiple different versions running).

**Comment by felipecrs** [comment] 2020-09-23 19:54
The:

```bash
alias code=code-insiders
```

Does not work for `git`, so for me it's pretty much useless.

```sh-session
$ alias code=code-insiders
$ GIT_EDITOR='code --wait' git config -e
hint: Waiting for your editor to close the file... code --wait: 1: code: not found
error: There was a problem with the editor 'code --wait'.
```

**Comment by jkeech** [comment] 2020-09-23 20:03
@felipecrs, that's true. The base image for Codespaces also sets up the Git editor in a similar way: https://github.com/microsoft/vscode-dev-containers/blob/fac5d14726b62983c3ebbe183457a6b85c8e386b/containers/codespaces-linux/.devcontainer/setup-user.sh#L23-L39

**Comment by felipecrs** [comment] 2020-09-23 20:24
> In fact, if you connect concurrently from both VS Code and VS Code Insiders, you'll see different results since one is stable and one is insiders.

Makes sense. So I ended up making my shim a bit smarter:

```sh
#!/bin/sh

get_in_path_except_current() {
  which -a "$1" | grep -v "$0" | head -1
}

code="$(get_in_path_except_current code)"

if [ -n "$code" ]; then
  exec "$code" "$@"
elif [ "$(command -v code-insiders)" ]; then
  exec code-insiders "$@"
else
  echo "code is not installed" >&2
  exit 127
fi
```

**Comment by felipecrs** [comment] 2020-09-23 20:26
> @felipecrs, that's true. The base image for Codespaces also sets up the Git editor in a similar way: https://github.com/microsoft/vscode-dev-containers/blob/fac5d14726b62983c3ebbe183457a6b85c8e386b/containers/codespaces-linux/.devcontainer/setup-user.sh#L23-L39

Interesting, but my dotfiles seems to be supressing it. I suppose that's not the desired behavior, right? (probably everyone who have their dotfiles will have the `core.editor` set in their `.gitconfig`).

**Comment by felipecrs** [comment] 2020-09-23 20:29
So perhaps this configuration should be made **after** dotfiles installation, or instead of setting it through `.gitconfig`, you could add a new env variable: `GIT_EDITOR='code-insiders --wait'`. That will take precedence over the editor set in the gitconfig.

But I wonder if that's not so intrusive, I mean, maybe the users prefer to use `vi` anyway. Hahaha

**Comment by felipecrs** [comment] 2020-09-23 20:35
Or, even better, you add this shim to all the containers somewhere in PATH (`/usr/local/bin` for example), so that issue would be gone for all.

**Comment by jkeech** [comment] 2020-09-23 21:21
@felipecrs, the philosophy we have taken is to provide an opinionated default experience (such as setting the git editor in the base docker file, customizing the bash prompt, installing some languages, SDKs, and runtimes, etc), but to also give users full control and customizability where we don't get in the way. The way this plays out is that dotfiles can always layers on top of the image config, and in custom container configurations we do not inject opinionated configuration such as the git editor config. 

We believe this provides a good balance of a great out-of-the-box experience for new users and common scenarios while remaining flexible enough for a large set of scenarios and users to use whatever tools and workflows work best for them.

I think it would be reasonable for us to document how to easily configure these things in a custom container, but we wouldn't want to automatically inject scripts/variables like this just in case users might want to use them.

**Comment by felipecrs** [comment] 2020-09-23 21:25
> just in case users might want to use them

Aren't we talking about all the users who:

1. Have dotfiles
2. Use `code` as their default editor in their dotfiles
3. Use GitHub Codespaces where `code` is not available by default, but instead we have `code-insiders`

This seems to be very wide to me.

**Comment by jkeech** [comment] 2020-09-23 21:36
> However, if you say that in the short future the default channel for Visual Studio Code in GitHub Codespaces will be switched to the stable, then I believe that it simply doesn't worth it.

That's correct. We will be switching to stable as the default channel before Codespaces leaves Beta status, and VS Code will be added a channel selector from within the editor so you can switch back and forth easily.

> 3\. Use GitHub Codespaces where `code` is not available by default, but instead, we have `code-insiders`?

The default image *does* make `code` available in the terminal and set as the git editor. You do not need to do anything else to configure this separately.

The only cases where that wouldn't be true are if you
1) override the default settings with custom dotfiles
2) use a custom image in devcontainer.json

Both of those scenarios are examples of where we allow users to have full control based on the philosophy I outlined. In other words, the `code` alias does work out of the box in GitHub Codespaces unless you use advanced configuration to override that, which we have no plans to block.

**Comment by felipecrs** [comment] 2020-09-23 21:40
> unless you use advanced configuration to override that, which we have no plans to block.

Do you agree that adding this shim in the container does not block anything, but only help to prevent issues? This is not about overriding the user's `.gitconfig`.

**Comment by jkeech** [comment] 2020-09-23 21:52
> Do you agree that adding this shim in the container does not block anything, but only help to prevent issues? We're not about overriding any user's configuration.

No, I do not think we should be injecting extra (unused) scripts/binaries/etc into custom containers. We should only inject the minimum needed to run Codespaces and stay out of the way beyond that, which aligns with the philosophy I've outlined above. The purpose of custom containers is to enable users to tweak things from the default config. If they want the default config, they should use that. If they want to customize, we respect that decision and do not interfere.

I'm going to go ahead and close this issue as Won't Fix since the original post's behavior is by design and a couple solutions have been listed. Thanks!

For future reference, support for GitHub Codespaces is moving to [GitHub Community](https://github.community/c/codespaces-beta/45), so that's a great place to ask questions or make feature requests for GitHub Codespaces.

**Closed by jkeech** 2020-09-23 21:52 UTC

**Comment by felipecrs** [comment] 2020-09-23 21:55
Ok, despite I don't see a true reason not to do it in your point. Thanks anyway.

**Comment by felipecrs** [comment] 2020-09-23 21:57
Got it, so the problem is about injecting it into custom containers. I'll open a new issue in the containers definition to consider adding it to the base containers so. Thanks!
