### ISSUE TITLE
my codespace does not resume

### ISSUE THREAD

**Issue by xuerui911** [MicrosoftDocs/vscodespaces#763] opened 2020-08-23 06:32 UTC
I have the same problem as #514 

Resume Codespace
Looks like this is taking a little longer than usual but your Codespace will be ready soon
![image](https://user-images.githubusercontent.com/46309554/90972638-66504300-e54d-11ea-8372-63a0ecdd83c0.png)

my container url is https://online.visualstudio.com/environment/1600981e-6009-4d0a-9a12-42ae69f3c8d1

Thank you for your help!!!

**Comment by smvanderweide** [comment] 2020-08-25 02:10
Hello! We took a look at your codespace, and it looks like the issue is likely to have been a transient error. Could you try shutting down your environment and then resuming it again, and let us know if the resume still fails.

**Comment by xuerui911** [comment] 2020-08-25 05:39
> Hello! We took a look at your codespace, and it looks like the issue is likely to have been a transient error. Could you try shutting down your environment and then resuming it again, and let us know if the resume still fails.

There is only 'suspend' option, but no 'shut down'. I tried it, but it still failed.

**Comment by smvanderweide** [comment] 2020-08-26 17:59
The suspend option was the one I wanted you to try, thank you for doing that. We are still looking into why it is failing, and will update you when we know something more.

**Comment by smvanderweide** [comment] 2020-08-26 21:45
I think we have fixed your issue, and if you suspend and resume it should now connect. The codespace was looking for certs in the incorrect directory. We suspect this is because there were two copies of OpenSSL installed. Is there anything you did that may have installed a second copy of OpenSSL?

**Comment by xuerui911** [comment] 2020-08-27 19:31
> 
> 
> I think we have fixed your issue, and if you suspend and resume it should now connect. The codespace was looking for certs in the incorrect directory. We suspect this is because there were two copies of OpenSSL installed. Is there anything you did that may have installed a second copy of OpenSSL?

Oh sorry, I just have a little obsessive-compulsive disorder, I always like updated things. 
I am currently in the water supply and drainage industry, and I am learning programming to switch to the IT industry, so I am only a prospective programmer. This codespace is used by me to learn hadoop. And I have not been exposed to the production environment, so I always update all the software to the latest. 
I modified the /etc/apt/sources.list file in the container, and changed all 'stretch' to 'buster'. 
When it was updated, it prompted a software that has not been updated. The software that has not been successfully upgraded should be OpenSSL.

**Comment by jkeech** [comment] 2020-08-27 19:37
@xuerui911, to clarify, the version of OpenSSL that was on the PATH did not have any valid CA certificates configured, so the issue in your Codespace was that the agent we run inside to provide connectivity to the Codespace was not able to make outbound SSL connections since it could not validate cert chains.

In this case, the misconfigured OpenSSL caused the Codespaces agent to not be able to provide connectivity to the container, which is why it couldn't restart.

We have some plans to change the architecture of how the agent works by moving it out of the container and into the host VM. This change should prevent situations like this, where even if the container itself is misconfigured, the host should be able to provide connectivity to the container. That's a fairly large change, so we have to be careful about how to roll it out, but that's the direction we are heading. Hope that helps!

**Comment by xuerui911** [comment] 2020-08-27 19:46
> 
> 
> @xuerui911, to clarify, the version of OpenSSL that was on the PATH did not have any valid CA certificates configured, so the issue in your Codespace was that the agent we run inside to provide connectivity to the Codespace was not able to make outbound SSL connections since it could not validate cert chains.
> 
> In this case, the misconfigured OpenSSL caused the Codespaces agent to not be able to provide connectivity to the container, which is why it couldn't restart.
> 
> We have some plans to change the architecture of how the agent works by moving it out of the container and into the host VM. This change should prevent situations like this, where even if the container itself is misconfigured, the host should be able to provide connectivity to the container. That's a fairly large change, so we have to be careful about how to roll it out, but that's the direction we are heading. Hope that helps!

Thank you for your work and help for me.
I look forward to the open source community and docker company working together to make the container more secure while also making it easier to use inside the container.
I hope that your work can move forward steadily towards a better vision.

**Closed** 2020-08-28 17:59 UTC
