### ISSUE TITLE
Port forwarding web app results in 400

### ISSUE THREAD

**Issue by misolori** [MicrosoftDocs/vscodespaces#117] opened 2019-11-07 19:22 UTC
Not sure if related to #10 

Steps:
1. Install gatsby via `npm install -g gatsby-cli`
2. Setup template `gatsby new gatsby-starter-default https://github.com/gatsbyjs/gatsby-starter-default`
3. cd into new directory, reload vso via `code-insiders gatsby-starter-default`
4. run `gatsby develop`
5. Copy port forward url from explorer and open in browser
6. 🐛  Page ends up blank

Here's the console log, lots of 504 + 400 errors:
![image](https://user-images.githubusercontent.com/35271042/68420137-88a8d980-0150-11ea-8789-4974158dc654.png)

**Comment by jkeech** [comment] 2019-11-07 22:05
It looks like this is caused by #19, since Gatsby is using socket.io. The current port-forwarding implementation does not support web sockets. In the repro steps you gave, the GraphQL link when you run `gatsby develop` does load fine in the browser, and if you run `gatsby build` and `gatsby serve`, the static site also loads, which makes me think it's not related to the web server in this case, but rather the websockets limitation.

**Comment by hongaar** [comment] 2020-02-01 20:10
Support for web sockets during development is a must for developing web apps. Many (most?) stacks include webpack and many (most?) development stacks use webpack-dev-server, which relies on web sockets. Support for this in VSO would make it my go to tool for many new projects!

Another - related to this - issue I have is that the current port forwarding mechanism proxies all local ports to secure (https) endpoints, while the app was originally served over plain http. webpack-dev-server also uses insecure ws connections in this case, which fails because of security policies in the browser (not allowed to connect to ws:// on https:// page). Serving a local app over https would solve this but may not always be feasible for all stacks.

**Comment by Chuxel** [comment] 2020-05-18 16:27
This is also blocking the use of noVNC for a VS Code development container we're looking into.

**Comment by pelikhan** [comment] 2020-10-07 20:40
This is basically a show stopper if you use any modern front end framework that does hot-reloading (all the cool kids do it).

**Comment by plisy** [comment] 2020-10-07 20:49
@pelikhan at this point it should be resolved. Are you still facing issues? If so can you please provide more details?

Is the hot-reload server running on the same/different port than the main app?

**Comment by pelikhan** [comment] 2020-10-07 21:11
I launched a repo running ``gatsby develop`` and it blocked the socket.io request - which runs on the same port. This is pretty much the same setup as the gatsby starter otherwise the repro is in https://github.com/microsoft/jacdac-ts

**Comment by lostintangent** [comment] 2020-10-11 17:43
@plisy Do we still have known issues with Gatsby? We've been seeing a lot of users being successful with Gatsby + Codespaces, so I'm curious if there's a specific problem with @pelikhan's app?

**Comment by plisy** [comment] 2020-10-11 18:15
I think these might be the same issues we used to see with gatsby initially when we landed websocket support. Those have been fixed on gatsby side since then.

**Comment by pelikhan** [comment] 2020-10-11 18:54
I could not find any documented guidance around this issue.

________________________________

**Comment by lostintangent** [comment] 2020-10-30 23:43
Closing this issue as resolved, since I was just able to successfully run through the same steps. Please let us know if you're still running into any issues. Thanks!

**Closed by lostintangent** 2020-10-30 23:43 UTC
Labels: area: port forwarding, bug, fixed-gh
