### ISSUE TITLE
.NET Core dependency install failed!

### ISSUE THREAD

**Issue by amowu** [MicrosoftDocs/vscodespaces#326] opened 2020-03-03 07:32 UTC
This is my `devcontainer.json` file:

```json
{
  "image": "circleci/postgres:10-alpine"
}
```

And my container setup output: `.NET Core dependency install failed!`

![Screen Shot 2020-03-03 at 3 29 44 PM](https://user-images.githubusercontent.com/559351/75752511-d252ab00-5d63-11ea-8ae0-f549f9f5f3d4.png)

**Comment by jkeech** [comment] 2020-03-03 18:02
The VSO agent that provides the connection for the environment needs to be able to run inside the container. The agent is built using .NET Core, so the base image needs to be able to able to run the .NET Core runtime. Can you try using a different custom image that is not just alpine? We are working on providing some updated docs with clearer instructions on which dependencies are needed, and which types of images should work. /cc @nikmd23

**Comment by lostintangent** [comment] 2020-04-04 20:10
@jkeech Is this issue primarily with using Alpine base images? Since that Linux distro doesn’t include all the .NET Core dependencies our of the box? (whereas other distros like Ubuntu, Debian, etc. would)?

**Comment by jkeech** [comment] 2020-04-04 20:16
@lostintangent, I don't know exactly which distros work and which ones don't -- we need to do a bunch of testing and document the ones that work (as well as see if there's something we can do to make other distros work that we care about, if any of those fail). I believe @nikmd23 started some of that testing a while back.

Minimalistic images like alpine, busybox, etc are much more likely to not work out of the box than a full-fledged distro. Alpine seems like an interesting choice for a dev environment. For a runtime/production environment it makes sense, but at dev time, it would be missing a lot of tools that devs are used to running on the command line. So I'm not sure if alpine is something that we would want to put a lot of effort into trying to make work.

**Comment by lostintangent** [comment] 2020-10-11 19:23
Closing this as a duplicate of #458, which is tracking the fact that Codespaces doesn't support Alpine-based images.

**Closed by lostintangent** 2020-10-11 19:23 UTC
Labels: doc-bug
