### ISSUE TITLE
Big Bug suddenly internet is cutoff then code cant resume sooner

### ISSUE THREAD

**Issue by pawanpyakurel** [MicrosoftDocs/vscodespaces#787] opened 2020-09-04 01:50 UTC
I face the problem many times. When I am working with codeSpace and suddenly internet is down, then the codespace cant resume later, if I have some unsaved code. This is big big issues because i lost my uncommitted code.

**Comment by jkeech** [comment] 2020-09-11 05:38
Closing as a duplicate of #782. Let’s investigate on that issue. Thanks!

**Closed by jkeech** 2020-09-11 05:38 UTC
