### ISSUE TITLE
Gatsby JS Development - Blank Screen on forwarding port

### ISSUE THREAD

**Issue by waywardm** [MicrosoftDocs/vscodespaces#588] opened 2020-06-16 16:01 UTC
Regarding use of Gatsbyjs in VS Codespaces

I cannot seem to develop using the Gatsby Development command when it goes  to the forwarding port it is a blank screen. When you check the source it is loading the initial page but not injecting the code into the browser, as gatsbyjs is becoming ever more popular I would have thought this would need looking at, I have successfully managed using gitpod ide in the past.

**Comment by chkn** [comment] 2020-06-17 18:46
Does Gatsbyjs use websockets? Our current port forwarding solution in the browser has a lot of limitations. For instance, websocket connections don't work (see #196). You can get around that by installing the Codespaces extension in VS Code on the desktop and connecting from there.

**Comment by ravikumarpasupuleti** [comment] 2020-08-05 22:19
Is there a work around or fix for this to run gatsby projects?

**Comment by jkeech** [comment] 2020-08-05 22:21
@ravikumarpasupuleti The workaround for now is to connect from desktop VS Code to the Codespace. Full port forwarding will work correctly there.

**Comment by ravikumarpasupuleti** [comment] 2020-08-06 10:57
Thanks It worked @jkeech .

**Comment by lostintangent** [comment] 2020-09-11 04:37
Closing this as a duplicate of #117.

**Closed by lostintangent** 2020-09-11 04:37 UTC
Labels: area: port forwarding
