### ISSUE TITLE
Copy/Cut support for iOS/iPadOS

### ISSUE THREAD

**Issue by DAddYE** [MicrosoftDocs/vscodespaces#616] opened 2020-06-25 21:25 UTC
Hi all,

both on iOS and iPadOs 13, I'm unable to use copy/cut feature using Safari when using vso. My vscode configuration is available [here](https://gist.github.com/DAddYE/8d568f756f5a16587e8e835c130b2912).

**Comment by dmitryyankowski** [comment] 2020-06-26 05:36
Same here :/

**Comment by VincentDondain** [comment] 2020-08-25 21:19
From @DAddYE in https://github.com/MicrosoftDocs/vscodespaces/issues/768

> Currently the upstream vscode has on file vscode/src/vs/editor/browser/controller/textAreaHandler.ts this:
``` javascript
getScreenReaderContent: (currentState: TextAreaState): TextAreaState => {                                                                                                                                                                                                
                                 if (browser.isIPad) {                                                                                           
                                         // Do not place anything in the textarea for the iPad                                                   
                                         return TextAreaState.EMPTY;                                                                          
                                 }
```
> The return TextAreaState.EMPTY; prevents iPadOS to correctly copy/paste. Removing it allows fixes the issue.
> However, I have no idea why was there in the first place :)
> This should fix also the others issue related like #566

**Comment by VincentDondain** [comment] 2020-08-25 21:23
@DAddYE that's a very interesting find! However, it looks like it has been removed since https://github.com/microsoft/vscode/commit/b3fba742c5846997eb7ef1f36a1860588eff681a (July 3rd). I'll check why this doesn't seem to have fixed the issue.

**Comment by DAddYE** [comment] 2020-08-26 18:03
> @DAddYE that's a very interesting find! However, it looks like it has been removed since [microsoft/vscode@b3fba74](https://github.com/microsoft/vscode/commit/b3fba742c5846997eb7ef1f36a1860588eff681a) (July 3rd). I'll check why this doesn't seem to have fixed the issue.

Maybe isn't yet deployed? Tested it with `code-server` and works well on latest iPadOs

**Comment by VincentDondain** [comment] 2020-08-26 19:50
Yes, this is a very recent fix that'll be deployed soon. Glad to hear it works well for you.

**Comment by VincentDondain** [comment] 2020-08-31 18:19
Confirmed, this does seem to be fixed by the commit mentioned above. Closing this issue (feel free to reopen if you're still experiencing issues with Copy & Paste on iOS/iPadOS).

**Closed by VincentDondain** 2020-08-31 18:19 UTC
Labels: area: browser support, area: web editor, iOS/iPadOS
