### ISSUE TITLE
Proxy calls to localhost to the respective port-forwarding url

### ISSUE THREAD

**Issue by janus-reith** [MicrosoftDocs/vscodespaces#707] opened 2020-08-03 11:20 UTC
Some projects I work on consist of multiple services that need to be reachable from the client.
For example, a frontend runs on localhost:4000, an API that needs to be called from the client's browser runs on localhost:3000. another service, initiating an oauth flow, is reached by the browser redirecting to localhost:4444.

Currently, I can forward all three ports and can directly reach the frontend on port 3000 of the server by using its forwarded url when using the web version of codespaces. Fetch calls and Redirects however will still point to localhost - Would it be possible to seamlessly rewrite them to forwarded urls?

To be able to work with a broad range of possibly restricted, or also in general exchangeable devices, I'd like to avoid client side solutions to redirect these.

**Comment by plisy** [comment] 2020-08-06 14:04
We are planning to add redirect rewrite support.

Fetch calls are more problematic as that would require us to alter the client code in transport which so far we want to avoid as much as possible.

We’ll provide X-Forwarded-Host you could use to construct those fetch calls for the right host.

Would that solve your problem?

**Comment by janus-reith** [comment] 2020-08-07 11:33
@plisy Thanks, redirects and rewrites sound great.
I get that interfering with the client code should be avoided where possible.

Regarding `X-Forwarded-Host`, what url would that contain? I'm wondering because each forwarded port would get an own url that includes the port, so how would my frontend on a forwarded port 4000 know about the forwarded port 3000 from that?
However, if it works for the purpose somehow, as you pointed out it would still require changes to my codebase, which I could also do now to circumvent that error(e.g. parse the current url in client code and alter it if is not localhost but a forwarded one and replace the current port url segment with my target port), although  using `X-Forwarded-Host` certainly would be a more precise solution if it works.

I'd still like to explore a solution that would work with any arbitrary codebase consisting of multiple service on localhost, and I also see no technical solution for this that would not either involve further steps on the client environment itself, or altering the code meant to be sent to the client.
I wonder if this could be put under an optional flag, so you would need to explicitly enable that feature yourself, but in turn if it results in errors you would also know where they might come from?

**Comment by sebastianrogers** [comment] 2020-08-25 10:54
When attempting OAUTH authentication using Visual Studio Code in the browser I get the following:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <environment include="Development">
        <link rel="stylesheet" href="/site.css" />
    </environment>
</head>
<body>
        <div class="vsonline-titlebar part">
            <div class="vsonline-titlebar__caption" aria-label="Visual Studio logo">
                <div class="vsonline-titlebar__logo"></div>
                <div class="vsonline-titlebar__separator"></div>
                <div class="vsonline-titlebar__caption-text">
                    Visual Studio Codespaces
                </div>
            </div>
        </div>
    <div>
        
<!doctype html>
<html lang="en">
<head>
    <title>Port Forwarding exceptions...</title>
</head>
<body>
    <div class="vsonline__redirect">
                <p>PortForwarder Failed due to unknown reason.</p>
                <a href="https://online.visualstudio.com/port-forwarding-sign-in/c7770b59-c6fe-4058-a181-ca7f4626a331?path=%2ferror&amp;port=3000&amp;cid=09b1f47652d93c9e7c41e961efba0474">Reload</a>
    </div>
</body>
</html>
    </div>
</body>
</html>
```

**Comment by plisy** [comment] 2020-08-25 19:05
@sebastianrogers just make sure I understand correctly, you are developing an application in a codespace and that application uses OAuth for authentication?

**Comment by sebastianrogers** [comment] 2020-08-26 08:30
@plisy yes that is right.

The problem can be recreated by using the Next Auth Example https://github.com/nextauthjs/next-auth-example code

**Comment by plisy** [comment] 2020-08-26 15:54
The problem is in current port forwarding solution. We'll be rolling out a completely new service for port forwarding in coming weeks where this should no longer be a problem.

**Comment by sebastianrogers** [comment] 2020-08-26 19:57
Excellent I look forward to it.

**Comment by lostintangent** [comment] 2020-10-11 18:38
Closing this as resolve since we've since rolled out the new port forwarding solution that @plisy was referring to. Please re-open this if you're still running into problems. Also, @plisy please re-open this if I'm erroneously closing it prematurely. Thanks!

**Closed by lostintangent** 2020-10-11 18:38 UTC
